name: casino_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/images/splash_screen/
    - assets/images/login/
    - assets/images/games/
    - assets/images/dashboard/
    - assets/images/nav_bar/
    - assets/images/spin/
    - assets/images/dashboard/
    - assets/images/wallet/
    - assets/animation/
    - assets/font-family/
    - assets/images/logo/
    - assets/animation/

  fonts:
    - family: Semakin
      fonts:
        - asset: assets/font-family/Semakin.otf
    - family: Inter
      fonts:
        - asset: assets/font-family/Inter-Regular.ttf